# exposed ports
ports:
- port: 8080
  onOpen: open-preview

#docker image to use
image:
  file: Dockerfile

# start up tasks
tasks:
- before: chmod a+x ./gradlew
  init: >
    mysql <db.sql && 
    ./gradlew clean build
  command: java -jar target/*.jar

 
